### ISSUE TITLE
Functie 'Toon alleen geselecteerde objecten' lijkt niet altijd te werken

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-commons#267]
https://github.com/IDgis/CRS2/issues/211

**Comment by HermanAssink** [comment]
Gedrag is verschilt tussen selectie vanuit CRS2 en vanuit viewer. @LindaVels: Hoe zou het gedrag eigenlijk moeten zijn? Soms werkt de knop niet als je in de viewer een object hebt geselecteerd.

**Comment by LindaVels** [comment]
We beginnen hier tegen de grenzen van het systeem aan te lopen. Bij filteren vanuit CRS2 krijg ik de volgende foutmelding:

HTTP Error 404.15 - Not Found
The request filtering module is configured to deny a request where the query string is too long.

Most likely causes:
Request filtering is configured on the Web server to deny the request because the query string is too long.

De query die vanuit CRS2 wordt verstuurd is lang, deze lengte wordt  verdubbeld voor de union voor de selectie. In het geval van filtering zelfs verdriedubbeld omdat er nog een where clause is ingebouwd die ervoor zorgt dat de selectie een subset is van de gefilterde objecten.

**Comment by LindaVels** [comment]
De fout treedt niet meer op als de sql wms en wfs lagen via een interne url worden opgevraagd. . Dus niet meer via IIS lopen.
Oplossing is om ervoor te zorgen dat er interne urls worden gebruikt voor de speciale sql lagen.

**Comment by HermanAssink** [comment]
Met interne urls wordt bedoeld urls direct naar Tomcat, dus niet via IIS
